title: "NinjaBlog"
author: "Jack Locke"
description: "Musings about robots, hacking, technology, futurism, philosophy, movies and more! <|>"

twitter_username: "ninjajoe9"
github_username: "ninjajoe9"
linkedin_username: "josephrlocke"

##########

theme: jekyll-theme-hacker

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true
  
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
